# Generated by Django 3.0.7 on 2020-07-06 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200617_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
